[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[package]
name = "pixi_toml_test"
version = "1.0.0"
description = "TEST"
license = "Apache-2.0"
homepage = "https://git.smart-robotics.nl/smart-robotics/sr_installation_tools"
repository = "https://git.smart-robotics.nl/smart-robotics/sr_installation_tools.git"
documentation = "https://docs.smart-robotics.nl/sr_installation_tools/index.html"
authors = ["Daniel Claes <dclaes@smart-robotics.nl>"]

[package.build.backend]
name = "pixi-build-python"
version = "*"
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[package.host-dependencies]
hatchling = ">=1.27.0,<2"
python = ">=3.11,<3.14"

[package.run-dependencies]
python = ">=3.11,<3.14"

[dependencies]
pixi_toml_test = { path = "." }

[tasks]
